import { LookupResult, FeedItem } from './types'
export const DEMO_DB: Record<string, Record<string, LookupResult>> = {
  ips:{'185.220.101.34':{indicator:'185.220.101.34',type:'ip',verdict:'malicious',confidence:92,country:'DE',isp:'Tor Exit Node',firstSeen:'2024-08-12',lastSeen:'2026-09-15',reports:847,categories:['Tor Exit Node','Brute Force'],sources:[{name:'AbuseIPDB',detail:'Score: 100/100, 847 reports'},{name:'OTX',detail:'23 pulses'},{name:'VirusTotal',detail:'14/87 flagged'}]},'8.8.8.8':{indicator:'8.8.8.8',type:'ip',verdict:'clean',confidence:98,country:'US',isp:'Google LLC',firstSeen:'2009-01-01',lastSeen:'2026-09-17',reports:2,categories:['Public DNS'],sources:[{name:'AbuseIPDB',detail:'Score: 0/100'},{name:'OTX',detail:'0 pulses'},{name:'VirusTotal',detail:'0/87 flagged'}]},'91.121.87.10':{indicator:'91.121.87.10',type:'ip',verdict:'suspicious',confidence:67,country:'FR',isp:'OVH SAS',firstSeen:'2025-02-20',lastSeen:'2026-09-10',reports:34,categories:['Port Scanning','SSH Brute Force'],sources:[{name:'AbuseIPDB',detail:'Score: 45/100, 34 reports'},{name:'OTX',detail:'3 pulses'},{name:'VirusTotal',detail:'2/87 flagged'}]}},
  domains:{'malware-c2.example.net':{indicator:'malware-c2.example.net',type:'domain',verdict:'malicious',confidence:96,registrar:'Namecheap',firstSeen:'2026-07-01',lastSeen:'2026-09-14',reports:128,categories:['C2 Server','Phishing'],sources:[{name:'OTX',detail:'45 pulses'},{name:'VirusTotal',detail:'31/87 flagged'}]},'google.com':{indicator:'google.com',type:'domain',verdict:'clean',confidence:99,registrar:'MarkMonitor',firstSeen:'1997-09-15',lastSeen:'2026-09-17',reports:0,categories:['Search Engine'],sources:[{name:'OTX',detail:'0 pulses'},{name:'VirusTotal',detail:'0/87 flagged'}]}},
  hashes:{'44d88612fea8a8f36de82e1278abb02f':{indicator:'44d88612fea8a8f36de82e1278abb02f',type:'hash',verdict:'malicious',confidence:88,fileName:'eicar_test.com',fileType:'EICAR Test File',firstSeen:'2003-06-15',lastSeen:'2026-09-16',categories:['Test File','EICAR'],sources:[{name:'VirusTotal',detail:'62/72 flagged'},{name:'OTX',detail:'12 pulses'}]}}
}
export const FEED_DATA: FeedItem[] = [
  {title:'Tor exit node surge in DACH region',desc:'Multiple new Tor exit nodes. Correlates with SSH brute-force uptick.',sev:'high',source:'OTX',time:'2h ago'},
  {title:'Cobalt Strike beacon infrastructure update',desc:'New C2 domains registered through Namecheap in the last 48 hours.',sev:'crit',source:'OTX',time:'5h ago'},
  {title:'Credential stuffing targeting SaaS',desc:'Distributed attack via residential proxies. 200+ IPs targeting Okta and Azure AD.',sev:'high',source:'AbuseIPDB',time:'8h ago'},
  {title:'New Lumma Stealer variant',desc:'Updated loader bypasses Windows Defender. Hash indicators added.',sev:'crit',source:'VT',time:'12h ago'},
  {title:'DNS tunneling detection update',desc:'Community Snort signatures for DNS-based exfiltration.',sev:'med',source:'OTX',time:'1d ago'},
  {title:'AsyncRAT via Discord CDN',desc:'Multi-stage distribution. Final payload: AsyncRAT with scheduled task persistence.',sev:'high',source:'VT',time:'2d ago'},
]
